version: '3.1'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db-admin
      POSTGRES_PASSWORD: db-password
      POSTGRES_DB: widgets

  vault:
    image: vault
    ports:
      - 8200:8200
    environment:
      - "SKIP_SETCAP=true"
      - "VAULT_LOCAL_CONFIG={\"disable_mlock\": true}"
      - "VAULT_DEV_ROOT_TOKEN_ID=root-token"